#! /usr/bin/env python

import os, sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'TrayLib'))
sys.path.insert(
    0, os.path.join(os.path.dirname(__file__), 'rox-lib', 'ROX-Lib2', 'python')
)

import rox

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

from apptray import PROJECT, SITE

rox.setup_app_options(PROJECT, 'Options.xml', SITE)

from traylib.main import Main
from traylib import ICON_THEME
from apptray.main import AppTray

ICON_THEME.append_search_path(os.path.join(rox.app_dir, 'icons'))

Main(PROJECT).mainloop(sys.argv, AppTray)
